name = "Gyuho Lee"
license = "MIT"
licenselink = "https://github.com/gyuho/gyuho.github.io/blob/master/LICENSE.md"
description = "Gyuho Lee"
homepage = "https://github.com/gyuho/gyuho.github.io"
tags = [
  "blog",
  "minimal",
  "minimalist",
  "responsive",
  "simple",
  "clean",
  "personal"
]
features = [
  "analytics",
  "favicon",
  "pagination",
  "single-column",
  "syntax-highlighting"
]
min_version = "0.32"

[author]
  name = "Gyuho Lee"
  homepage = "https://gyuho.github.io"

[original]
  author = "Luiz F. A. de Prá"
  homepage = "https://luizdepra.com"
  repo = "https://github.com/luizdepra/hugo-coder"